---
homeassistant:
  # Name of the location where Home Assistant is running
  name: MHome
  # Location required to calculate the time the sun rises and sets
  latitude: !secret latitude
  longitude: !secret longitude
  # Impacts weather/sunrise data
  elevation: 18
  # metric ftw
  unit_system: metric
  time_zone: Europe/Oslo
  customize: !include customize.yaml

group: !include groups.yaml

# Enables the frontend
frontend:

ios:

emulated_hue:
  listen_port: 80

recorder:
  purge_days: 5

http:
  # Uncomment this to add a password (recommended!)
  api_password: !secret http_password
  use_x_forwarded_for: True
  base_url: https://home.means.no
  cors_allowed_origins:
    - google.com
    - home-assistant.io

telegram_bot:
  platform: webhooks
  api_key: !secret telegram_api_key
  allowed_chat_ids:
    - 173232900
    - -217446614
    - 357286587

# Checks for available updates
updater:

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time.
history:

# View all events in a logbook
logbook:

# Track the sun
sun:


# Configuration Panel
config:

# Weather Prediction
sensor:
  - platform: yr
  - platform: moon
  - platform: sabnzbd
    name: mhome
    host: 192.168.0.20
    port: 8090
    api_key: !secret sabnzbd_api_key
    monitored_variables:
      - 'current_status'
      - 'queue_size'
      - 'queue_remaining'
  - platform: plex
    host: 192.168.0.20

binary_sensor:
  - platform: workday
    country: 'NO'
  - platform: ping
    host: 192.168.0.20
    name: Ping MHub
maxcube:
  host: 192.168.0.101

# notifications
notify:
  - name: telegram
    platform: telegram
    api_key: !secret telegram_api_key
    chat_id: -217446614
  - name: telegram_marcus
    platform: telegram
    api_key: !secret telegram_api_key
    chat_id: 173232900

media_player:
  - platform: plex
  - platform: lg_netcast
    host: 192.168.0.132
    access_token: !secret plex_access_token
  - platform: apple_tv
    host: 192.168.0.126
    login_id: !secret lg_login_id

ifttt:
  key: !secret ifttt_key

device_tracker:
  - platform: ddwrt
    host: 192.168.0.1
    username: admin
    password: !secret ddwrt_password
  - platform: ddwrt
    host: 192.168.0.3
    username: admin
    password: !secret ddwrt_password2

switch:
  - name: Loddebolt
    platform: orvibo
    host: 192.168.0.132
  - platform: command_line
    switches:
      livingroom_light:
        command_on: nodejs ~/.homeassistant/lights.js on
        command_off: nodejs ~/.homeassistant/lights.js off
        friendly_name: Family room light
  - platform: broadlink
    host: 192.168.0.30
    mac: 34:EA:34:E4:7C:CE
    type: rm2
    switches:
      eva_room:
        friendly_name:  Eva's room
        command_off: '6RRGAN8JFgkWCQkWCRYJFgkWCRYWCQkWFgkWCRYJCRYJFhYJFgkJFhYJFgkJFhYJCRYJFhYJFgkWCRYJCRYJFhYJFgkWCQkAAUjpFEYA3wkWCRYJCRYJFgkWCRYJFhYJCRYWCRYJFgkJFgkWFgkWCQkWFgkWCQkWFgkJFgkWFgkWCRYJFgkJFgkWFgkWCRYJCQABSOkURgDfCRYJFgkJFgkWCRYJFgkWFgkJFhYJFgkWCQkWCRYWCRYJCRYWCRYJCRYWCQkWCRYWCRYJFgkWCQkWCRYWCRYJFgkJAAFI6RRGAN8JFgkWCQkWCRYJFgkWCRYWCQkWFgkWCRYJCRYJFhYJFgkJFhYJFgkJFhYJCRYJFhYJFgkWCRYJCRYJFhYJFgkWCQkAAUjpFEYA3wkWCRYJCRYJFgkWCRYJFhYJCRYWCRYJFgkJFgkWFgkWCQkWFgkWCQkWFgkJFgkWFgkWCRYJFgkJFgkWFgkWCRYJCQABSOkURgDfCRYJFgkJFgkWCRYJFgkWFgkJFhYJFgkWCQkWCRYWCRYJCRYWCRYJCRYWCQkWCRYWCRYJFgkWCQkWCRYWCRYJFgkJAAFI'
        command_on: '6RRGAN8JCRYWCQkWFgkJFgkWFgkJFhYJFgkJFgkWFgkWCQkWFgkJFhYJCRYWCRYJFgkWCQkWFgkWCRYJCRYWCRYJFgkJFgkAAUjpFEYA3wkJFhYJCRYWCQkWCRYWCQkWFgkWCQkWCRYWCRYJCRYWCQkWFgkJFhYJFgkWCRYJCRYWCRYJFgkJFhYJFgkWCQkWCQABSOkURgDfCQkWFgkJFhYJCRYJFhYJCRYWCRYJCRYJFhYJFgkJFhYJCRYWCQkWFgkWCRYJFgkJFhYJFgkWCQkWFgkWCRYJCRYJAAFI6RRGAN8JCRYWCQkWFgkJFgkWFgkJFhYJFgkJFgkWFgkWCQkWFgkJFhYJCRYWCRYJFgkWCQkWFgkWCRYJCRYWCRYJFgkJFgkAAUjpFEYA3wkJFhYJCRYWCQkWCRYWCQkWFgkWCQkWCRYWCRYJCRYWCQkWFgkJFhYJFgkWCRYJCRYWCRYJFgkJFhYJFgkWCQkWCQABSOkURgDfCQkWFgkJFhYJCRYJFhYJCRYWCRYJCRYJFhYJFgkJFhYJCRYWCQkWFgkWCRYJFgkJFhYJFgkWCQkWFgkWCRYJCRYJAAFI'
      milla_room:
        friendly_name:  Milla's room
        command_on: '6RRGAN8JFgkWCRYJFgkJFhYJFgkJFhYJFgkJFgkWFgkWCRYJFgkJFhYJCRYWCRYJCRYWCRYJCRYJFhYJFgkWCRYJCRYJFgkAAUjpFEYA3wkWCRYJFgkWCQkWFgkWCQkWFgkWCQkWCRYWCRYJFgkWCQkWFgkJFhYJFgkJFhYJFgkJFgkWFgkWCRYJFgkJFgkWCQABSOkURgDfCRYJFgkWCRYJCRYWCRYJCRYWCRYJCRYJFhYJFgkWCRYJCRYWCQkWFgkWCQkWFgkWCQkWCRYWCRYJFgkWCQkWCRYJAAFI6RRGAN8JFgkWCRYJFgkJFhYJFgkJFhYJFgkJFgkWFgkWCRYJFgkJFhYJCRYWCRYJCRYWCRYJCRYJFhYJFgkWCRYJCRYJFgkAAUjpFEYA3wkWCRYJFgkWCQkWFgkWCQkWFgkWCQkWCRYWCRYJFgkWCQkWFgkJFhYJFgkJFhYJFgkJFgkWFgkWCRYJFgkJFgkWCQABSOkURgDfCRYJFgkWCRYJCRYWCRYJCRYWCRYJCRYJFhYJFgkWCRYJCRYWCQkWFgkWCQkWFgkWCQkWCRYWCRYJFgkWCQkWCRYJAAFI'
        command_off: '6RRGAN8JCRYJFgkWCRYJFhYJCRYJFgkWFgkJFhYJFgkWCQkWFgkWCRYJFgkJFgkWCRYJFgkWFgkJFgkWCRYJFhYJFgkWCQkAAUjpFEYA3wkJFgkWCRYJFgkWFgkJFgkWCRYWCQkWFgkWCRYJCRYWCRYJFgkWCQkWCRYJFgkWCRYWCQkWCRYJFgkWFgkWCRYJCQABSOkURgDfCQkWCRYJFgkWCRYWCQkWCRYJFhYJCRYWCRYJFgkJFhYJFgkWCRYJCRYJFgkWCRYJFhYJCRYJFgkWCRYWCRYJFgkJAAFI6RRGAN8JCRYJFgkWCRYJFhYJCRYJFgkWFgkJFhYJFgkWCQkWFgkWCRYJFgkJFgkWCRYJFgkWFgkJFgkWCRYJFhYJFgkWCQkAAUjpFEYA3wkJFgkWCRYJFgkWFgkJFgkWCRYWCQkWFgkWCRYJCRYWCRYJFgkWCQkWCRYJFgkWCRYWCQkWCRYJFgkWFgkWCRYJCQABSOkURgDfCQkWCRYJFgkWCRYWCQkWCRYJFhYJCRYWCRYJFgkJFhYJFgkWCRYJCRYJFgkWCRYJFhYJCRYJFgkWCRYWCRYJFgkJAAFI'
      master_bedroom:
        friendly_name: Master bedroom
        command_on: '6RRGAN8JCRYJFgkWCRYWCQkWCRYJFgkWFgkJFhYJFgkJFhYJCRYWCRYJCRYJFgkWCRYWCQkWFgkJFhYJFgkJFhYJCRYWCQkAAUjpFEYA3wkJFgkWCRYJFhYJCRYJFgkWCRYWCQkWFgkWCQkWFgkJFhYJFgkJFgkWCRYJFhYJCRYWCQkWFgkWCQkWFgkJFhYJCQABSOkURgDfCQkWCRYJFgkWFgkJFgkWCRYJFhYJCRYWCRYJCRYWCQkWFgkWCQkWCRYJFgkWFgkJFhYJCRYWCRYJCRYWCQkWFgkJAAFI6RRGAN8JCRYJFgkWCRYWCQkWCRYJFgkWFgkJFhYJFgkJFhYJCRYWCRYJCRYJFgkWCRYWCQkWFgkJFhYJFgkJFhYJCRYWCQkAAUjpFEYA3wkJFgkWCRYJFhYJCRYJFgkWCRYWCQkWFgkWCQkWFgkJFhYJFgkJFgkWCRYJFhYJCRYWCQkWFgkWCQkWFgkJFhYJCQABSOkURgDfCQkWCRYJFgkWFgkJFgkWCRYJFhYJCRYWCRYJCRYWCQkWFgkWCQkWCRYJFgkWFgkJFhYJCRYWCRYJCRYWCQkWFgkJAAFI'
        command_off: '6RRGAN8JFgkWCQkWCRYJFgkWFgkWCQkWFgkWCQkWFgkWCQkWCRYJFgkWCRYJFgkWCRYWCQkWFgkJFgkWFgkWCRYJCRYJFgkAAUjpFEYA3wkWCRYJCRYJFgkWCRYWCRYJCRYWCRYJCRYWCRYJCRYJFgkWCRYJFgkWCRYJFhYJCRYWCQkWCRYWCRYJFgkJFgkWCQABSOkURgDfCRYJFgkJFgkWCRYJFhYJFgkJFhYJFgkJFhYJFgkJFgkWCRYJFgkWCRYJFgkWFgkJFhYJCRYJFhYJFgkWCQkWCRYJAAFI6RRGAN8JFgkWCQkWCRYJFgkWFgkWCQkWFgkWCQkWFgkWCQkWCRYJFgkWCRYJFgkWCRYWCQkWFgkJFgkWFgkWCRYJCRYJFgkAAUjpFEYA3wkWCRYJCRYJFgkWCRYWCRYJCRYWCRYJCRYWCRYJCRYJFgkWCRYJFgkWCRYJFhYJCRYWCQkWCRYWCRYJFgkJFgkWCQABSOkURgDfCRYJFgkJFgkWCRYJFhYJFgkJFhYJFgkJFhYJFgkJFgkWCRYJFgkWCRYJFgkWFgkJFhYJCRYJFhYJFgkWCQkWCRYJAAFI'
      tv_lg:
        friendly_name: "Tv Power"
        command_off: 'JgBYAAABIJISExETETcSEhISEhQQFBETETcROBESEjcRNhM1EjcTNRMTERISNxEUERMSExE2EjYSNhM2EhIROBE3ETcREhITEgAFGwABH0oSAAwzAAEfShEADQU='
        command_on: 'JgBYAAABIJISExETETcSEhISEhQQFBETETcROBESEjcRNhM1EjcTNRMTERISNxEUERMSExE2EjYSNhM2EhIROBE3ETcREhITEgAFGwABH0oSAAwzAAEfShEADQU='

      tv_lg_hdmi1_hdmi2:
        friendly_name: "TV HDMI12"
        command_on: 'JgBIAAABIZMRExITEjYSExMRERURExEUEDkRNxEUEjYSNhM3ETcSNxITETgSNhI2ExMQExE4ETYSNxIUERMSExE4ETcRFBETEQANBQ=='
        command_off: 'JgBQAAABJJMSEhISETgSEhITEBMSEhMSETcSNxMREjcSNxI3EjcSOBETERITNhM2EhITERM2EzcRNxI3ExISEhI3EjcRExETEgAFLQABJEoRAA0FAAAAAAAAAAA='

      tv_lg_hdmi3:
        friendly_name: "TV HDMI3"
        command_on: 'JgBIAAABIZMSFBISETgRExEUERQQFBETEjcTNhMSETgRNxE3EjcROBM2ERMSFBE4ERMSNxM2EjUSFBE2ETgRExM2ExITEhATEwANBQ=='

      tv_lg_av1_av2:
        friendly_name: "LG Tv AV12"
        command_on: 'JgBIAAABIpQPFBITETgSEw8UEhQSEhEVDzgSOBAUETgQOQ84EjgRNxITETgSExA5EDgREhI3EhMROBMSEDkQFBETEjYTEhE4EQANBQ=='
        command_off: 'JgBIAAABH5YPFBETETgUERAUEBURFBATETgROBEUETcSNxE4ETcSOBISEBUQFREUEjUSFBA5ETcRNxE4ETkQOBAUEjcRFRAUEQANBQ=='

light:
  - platform: limitlessled
    bridges:
      - host: 192.168.0.120
        groups:
          - number: 1
            type: rgbw
            name: Office
          - number: 2
            type: white
            name: Family room
          - number: 4
            type: bridge-led
            name: Kitchen
  - platform: yeelight
    devices: 
      192.168.0.131:
        name: Living Room

xiaomi:
  gateways:
    - sid:
      key: !secret xiaomi_key


tts:
  - platform: google

automation: !include automations.yaml

influxdb:


weblink:
  entities:
    - name: Main router
      url: http://192.168.0.1/
    - name: Sonarr
      url: https://mhome.local:8989


script:
  goodnight:
    alias: Goodnight
    sequence:
      - event: LOGBOOK ENTRY
        event_data:
          name: Family
          message: Is going to bed
      - alias: Turn off tv
        service: media_player.turn_off
        data:
          entity_id: media_player.lg_tv_remote
      - alias: Turn off light
        service: switch.turn_off
        data:
          entity_id: switch.livingroom_light
